GSM8K_examples = [
    "Problem:\nNatalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May? \nSolution:\nNatalia sold 48/2 = <<48/2=24>>24 clips in May.\nNatalia sold 48+24 = <<48+24=72>>72 clips altogether in April and May. The answer is: 72 clips.\n\n\n",
    "Problem:\nWeng earns $12 an hour for babysitting. Yesterday, she just did 50 minutes of babysitting. How much did she earn? \nSolution:\nWeng earns 12/60 = $<<12/60=0.2>>0.2 per minute.\nWorking 50 minutes, she earned 0.2 x 50 = $<<0.2*50=10>>10. The answer is: 10.\n\n\n",
    "Problem:\nBetty is saving money for a new wallet which costs $100. Betty has only half of the money she needs. Her parents decided to give her $15 for that purpose, and her grandparents twice as much as her parents. How much more money does Betty need to buy the wallet? \nSolution:\nIn the beginning, Betty has only 100 / 2 = $<<100/2=50>>50.\nBetty's grandparents gave her 15 * 2 = $<<15*2=30>>30.\nThis means, Betty needs 100 - 50 - 30 - 15 = $<<100-50-30-15=5>>5 more. The answer is: 5.\n\n\n",
    "Problem:\nJulie is reading a 120-page book. Yesterday, she was able to read 12 pages and today, she read twice as many pages as yesterday. If she wants to read half of the remaining pages tomorrow, how many pages should she read? \nSolution:\nMaila read 12 x 2 = <<12*2=24>>24 pages today.\nSo she was able to read a total of 12 + 24 = <<12+24=36>>36 pages since yesterday.\nThere are 120 - 36 = <<120-36=84>>84 pages left to be read.\nSince she wants to read half of the remaining pages tomorrow, then she should read 84/2 = <<84/2=42>>42 pages. The answer is: 42.\n\n\n",
    "Problem:\nJames writes a 3-page letter to 2 different friends twice a week.  How many pages does he write a year? \nSolution:\nHe writes each friend 3*2=<<3*2=6>>6 pages a week\nSo he writes 6*2=<<6*2=12>>12 pages every week\nThat means he writes 12*52=<<12*52=624>>624 pages a year. The answer is: 624.\n\n\n",
    "Problem:\nMark has a garden with flowers. He planted plants of three different colors in it. Ten of them are yellow, and there are 80% more of those in purple. There are only 25% as many green flowers as there are yellow and purple flowers. How many flowers does Mark have in his garden? \nSolution:\n There are 80/100 * 10 = <<80/100*10=8>>8 more purple flowers than yellow flowers.\nSo in Mark's garden, there are 10 + 8 = <<10+8=18>>18 purple flowers.\nPurple and yellow flowers sum up to 10 + 18 = <<10+18=28>>28 flowers.\nThat means in Mark's garden there are 25/100 * 28 = <<25/100*28=7>>7 green flowers.\nSo in total Mark has 28 + 7 = <<28+7=35>>35 plants in his garden. The answer is: 35.\n\n\n",
    "Problem:\nAlbert is wondering how much pizza he can eat in one day. He buys 2 large pizzas and 2 small pizzas. A large pizza has 16 slices and a small pizza has 8 slices. If he eats it all, how many pieces does he eat that day? \nSolution:\nHe eats 32 from the largest pizzas because 2 x 16 = <<2*16=32>>32\nHe eats 16 from the small pizza because 2 x 8 = <<2*8=16>>16\nHe eats 48 pieces because 32 + 16 = <<32+16=48>>48. The answer is: 48.\n\n\n",
    "Problem:\nKen created a care package to send to his brother, who was away at boarding school.  Ken placed a box on a scale, and then he poured into the box enough jelly beans to bring the weight to 2 pounds.  Then, he added enough brownies to cause the weight to triple.  Next, he added another 2 pounds of jelly beans.  And finally, he added enough gummy worms to double the weight once again.  What was the final weight of the box of goodies, in pounds? \nSolution:\nTo the initial 2 pounds of jelly beans, he added enough brownies to cause the weight to triple, bringing the weight to 2*3=<<2*3=6>>6 pounds.\nNext, he added another 2 pounds of jelly beans, bringing the weight to 6+2=<<6+2=8>>8 pounds.\nAnd finally, he added enough gummy worms to double the weight once again, to a final weight of 8*2=<<8*2=16>>16 pounds. The answer is: 16.\n\n\n"
]

MATH_examples = [
    "Problem:\nHow many four-digit numbers greater than 2999 can be formed such that the product of the middle two digits exceeds 5?\nSolution:\nFor the first digit, there are seven choices (3, 4, 5, 6, 7, 8, or 9). For the last digit, there are ten choices (0 through 9).\n\nWe know that if either of the middle digits is 0, their product will not exceed 5. So, only consider pairs of middle digits formed from choosing two numbers between 1 and 9, inclusive. There are $9 \\cdot 9$ such pairs possible. The only pairs whose product will not exceed 5 are 11, 12, 13, 14, 15, 21, 22, 31, 41, and 51. Thus, there are $9 \\cdot 9 - 10 = 71$ ways in which we can choose the middle two digits.\n\nThus, there are $ 7 \\cdot 71 \\cdot 10 = \\boxed{4970}$ such numbers. \n\n\n",
    "Problem:\nDetermine the number of ways to arrange the letters of the word MADAM.\nSolution:\nFirst we count the arrangements if all the letters are unique, which is $5!$. Then since the M's and the A's are not unique, we divide by $2!$ twice for the arrangements of M's and the arrangements of A's, for an answer of $\\dfrac{5!}{2! \\times 2!} = \\boxed{30}$. \n\n\n",
    "Problem:\nCompute $\\dbinom{50}{2}$.\nSolution:\n$\\dbinom{50}{2} = \\dfrac{50!}{2!48!}=\\dfrac{50\\times 49}{2\\times 1}=\\boxed{1225}.$\n\n\n",
    "Problem:\nIf six people decide to come to a basketball game, but three of them are only 2/5 sure that they will stay for the entire time (the other three are sure they'll stay the whole time), what is the probability that at the end, at least 5 people stayed the entire time?\nSolution:\nThere are two cases: 5 people and 6 people stayed.\n\nCase 1: 5 people stayed the whole time.  The probability that exactly 2 of those that are unsure stayed the entire time is $\\binom{3}{2}\\times \\frac{2}{5}\\times\\frac{2}{5}\\times\\frac{3}{5}= 36/125$.\n\nCase 2: 6 people stayed the whole time.  The probability that all three unsure people stayed is $(2/5)^3 = 8/125$.\n\nThe sum of these probabilities is $\\boxed{\\frac{44}{125}}$.\n\n\n",
    "Problem:\nBertha has 6 daughters and no sons. Some of her daughters have 6 daughters, and the rest have none. Bertha has a total of 30 daughters and granddaughters, and no great-granddaughters. How many of Bertha's daughters and granddaughters have no daughters?\nSolution:\nBertha has $30 - 6 = 24$ granddaughters, none of whom have any daughters. The granddaughters are the children of $24/6 = 4$ of Bertha's daughters, so the number of women  having no daughters is $30 - 4 = \\boxed{26}$.\n\n\n",
    "Problem:\nWhat is $\\dbinom{n}{1}$ for any positive integer $n$?\nSolution:\n$\\dbinom{n}{1}=\\dfrac{n!}{1!(n-1)!}=\\boxed{n}$.  Also, $\\binom{n}{1}$ is the number of ways to choose 1 object out of $n$.  Since there are $n$ different objects, there are $\\boxed{n}$ ways to do this.\n\n\n",
    "Problem:\nStarting at $(0,0),$ an object moves in the coordinate plane via a sequence of steps, each of length one. Each step is left, right, up, or down, all four equally likely. Let $p$ be the probability that the object reaches $(2,2)$ in six or fewer steps. Given that $p$ can be written in the form $m/n,$ where $m$ and $n$ are relatively prime positive integers, find $m+n.$\nSolution:\nIt takes an even number of steps for the object to reach $(2,2)$, so the number of steps the object may have taken is either $4$ or $6$.\nIf the object took $4$ steps, then it must have gone two steps N and two steps E, in some permutation. There are $\\frac{4!}{2!2!} = 6$ ways for these four steps of occuring, and the probability is $\\frac{6}{4^{4}}$.\nIf the object took $6$ steps, then it must have gone two steps N and two steps E, and an additional pair of moves that would cancel out, either N/S or W/E. The sequences N,N,N,E,E,S can be permuted in $\\frac{6!}{3!2!1!} = 60$ ways. However, if the first four steps of the sequence are N,N,E,E in some permutation, it would have already reached the point $(2,2)$ in four moves. There are $\\frac{4!}{2!2!}$ ways to order those four steps and $2!$ ways to determine the order of the remaining two steps, for a total of $12$ sequences that we have to exclude. This gives $60-12=48$ sequences of steps. There are the same number of sequences for the steps N,N,E,E,E,W, so the probability here is $\\frac{2 \\times 48}{4^6}$.\nThe total probability is $\\frac{6}{4^4} + \\frac{96}{4^6} = \\frac{3}{64}$, and $m+n= \\boxed{67}$.\n\n\n",
    "Problem:\nMy grandpa has 10 pieces of art, including 3 prints by Escher. If he hangs the pieces of art in a row in a random order, what is the probability that all three pieces by Escher will be placed consecutively?\nSolution:\nTo count the number of ways of arranging the 10 pieces of art with the three Escher's consecutively, treat the three of them as one item. It is clear that we are then selecting the location of 1 item out of 8 total which can be done in $\\binom{8}{1}=8$ ways. There are also a total of $\\binom{10}{3}=120$ ways to place the three pictures without restrictions. Thus the probability that we want is $\\dfrac{8}{120}=\\boxed{\\dfrac{1}{15}}$.\n\n\n"
]
